import { Category, Product, Coupon, Banner, User, Order, Review } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-elec',
    name: 'Thiết Bị Điện Tử',
    slug: 'thiet-bi-dien-tu',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-fashion',
    name: 'Thời Trang Nam Nữ',
    slug: 'thoi-trang',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-accessory',
    name: 'Phụ Kiện Cao Cấp',
    slug: 'phu-kien',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-cosmetics',
    name: 'Mỹ Phẩm & Chăm Sóc',
    slug: 'my-pham',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500&auto=format&fit=crop&q=80',
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'iPhone 15 Pro Max 256GB',
    description: 'iPhone 15 Pro Max nổi bật sở hữu khung viền titan mỏng nhẹ lý tưởng, nút tác vụ Action tiện lợi cùng con chip A17 Pro tối tân cho hiệu năng cực đỉnh. Ngoài ra, chiếc iPhone này còn sở hữu camera zoom quang học 5X ấn tượng cùng thời lượng pin sử dụng đáng kinh ngạc lên đến 29 giờ.',
    categoryId: 'cat-elec',
    brand: 'Apple',
    originalPrice: 34990000,
    discountPrice: 29990000,
    image: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500&auto=format&fit=crop&q=80',
    ],
    colors: ['Titan tự nhiên', 'Xanh đen', 'Trắng tinh khôi'],
    sizes: ['256GB', '512GB'],
    variants: [
      { id: 'v1', color: 'Titan tự nhiên', size: '256GB', stock: 15 },
      { id: 'v2', color: 'Titan tự nhiên', size: '512GB', stock: 5 },
      { id: 'v3', color: 'Xanh đen', size: '256GB', stock: 12 },
      { id: 'v4', color: 'Xanh đen', size: '512GB', stock: 3 },
      { id: 'v5', color: 'Trắng tinh khôi', size: '256GB', stock: 0 }, // Out of stock
    ],
    specs: [
      { label: 'Màn hình', value: 'Super Retina XDR OLED, 6.7 inches' },
      { label: 'Vi xử lý', value: 'Apple A17 Pro 3nm' },
      { label: 'Camera sau', value: 'Chính 48MP, Phụ 12MP & 12MP' },
      { label: 'Hệ điều hành', value: 'iOS 17' },
      { label: 'Trọng lượng', value: '221g' },
    ],
    rating: 4.8,
    reviewCount: 3,
    salesCount: 45,
    dateAdded: '2026-05-10',
    featured: true,
    promo: true,
  },
  {
    id: 'prod-2',
    name: 'Tai Nghe Không Dây Bose QuietComfort Ultra',
    description: 'Bose QuietComfort Ultra mang lại trải nghiệm âm thanh không gian đột phá cùng công nghệ khử tiếng ồn CustomTune đỉnh cao. Thiết kế sang trọng với chất liệu đệm tai siêu êm ái, hỗ trợ chế độ Nhận biết thế giới xung quanh (Aware Mode) linh hoạt.',
    categoryId: 'cat-elec',
    brand: 'Bose',
    originalPrice: 10990000,
    discountPrice: 8990000,
    image: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=80',
    ],
    colors: ['Đen nhám', 'Trắng cát vàng'],
    sizes: ['Tiêu chuẩn'],
    variants: [
      { id: 'v6', color: 'Đen nhám', size: 'Tiêu chuẩn', stock: 25 },
      { id: 'v7', color: 'Trắng cát vàng', size: 'Tiêu chuẩn', stock: 10 },
    ],
    specs: [
      { label: 'Kết nối', value: 'Bluetooth 5.3 aptX Adaptive' },
      { label: 'Thời lượng pin', value: 'Lên tới 24 giờ liên tục' },
      { label: 'Kháng nước', value: 'IPX4' },
      { label: 'Hỗ trợ sạc nhanh', value: 'Sạc 15 phút nghe 2.5 giờ' },
    ],
    rating: 4.7,
    reviewCount: 1,
    salesCount: 22,
    dateAdded: '2026-04-15',
    featured: true,
    promo: true,
  },
  {
    id: 'prod-3',
    name: 'Áo Khoác Bomber Da Lộn Classic',
    description: 'Chất liệu da lộn mềm mịn lót lụa cao cấp mang tới sự ấm áp và thời thượng. Thiết kế cổ điển với khóa kéo kim loại không rỉ sét, hoàn hảo cho cả nam và nữ trong mọi phong cách hàng ngày.',
    categoryId: 'cat-fashion',
    brand: 'UrbanStyle',
    originalPrice: 1200000,
    discountPrice: 850000,
    image: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&auto=format&fit=crop&q=80',
    ],
    colors: ['Nâu bò', 'Xám đen'],
    sizes: ['M', 'L', 'XL'],
    variants: [
      { id: 'v8', color: 'Nâu bò', size: 'M', stock: 20 },
      { id: 'v9', color: 'Nâu bò', size: 'L', stock: 35 },
      { id: 'v10', color: 'Nâu bò', size: 'XL', stock: 15 },
      { id: 'v11', color: 'Xám đen', size: 'M', stock: 10 },
      { id: 'v12', color: 'Xám đen', size: 'L', stock: 8 },
      { id: 'v13', color: 'Xám đen', size: 'XL', stock: 2 }, // Low stock!
    ],
    specs: [
      { label: 'Chất liệu', value: '100% Da Lộn Phối Lụa Quai Chun' },
      { label: 'Xuất xứ', value: 'Việt Nam xuất khẩu' },
      { label: 'Hướng dẫn giặt', value: 'Giặt hấp khô chuyên dụng' },
    ],
    rating: 4.5,
    reviewCount: 2,
    salesCount: 50,
    dateAdded: '2026-05-01',
    featured: false,
    promo: true,
  },
  {
    id: 'prod-4',
    name: 'Giày Thể Thao Sneaker Active Pro 2.0',
    description: 'Đế giày bọt khí siêu nhẹ đàn hồi cực tốt, bọc vải dệt Knit cao cấp siêu thoáng khí, bảo vệ cổ chân bằng gót đệm đa lớp êm ái. Rất thích hợp cho chạy bộ dã ngoại hay đi bộ công sở.',
    categoryId: 'cat-fashion',
    brand: 'AeroStride',
    originalPrice: 2150000,
    discountPrice: 1590000,
    image: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop&q=80',
    ],
    colors: ['Đỏ lửa', 'Xám xi măng'],
    sizes: ['39', '40', '41', '42'],
    variants: [
      { id: 'v14', color: 'Đỏ lửa', size: '40', stock: 8 },
      { id: 'v15', color: 'Đỏ lửa', size: '41', stock: 12 },
      { id: 'v16', color: 'Đỏ lửa', size: '42', stock: 4 },
      { id: 'v17', color: 'Xám xi măng', size: '39', stock: 18 },
      { id: 'v18', color: 'Xám xi măng', size: '40', stock: 14 },
      { id: 'v19', color: 'Xám xi măng', size: '41', stock: 22 },
    ],
    specs: [
      { label: 'Độ cao đế', value: '3.5 cm' },
      { label: 'Trọng lượng', value: '240g / chiếc' },
      { label: 'Công nghệ', value: 'AeroFoat Cushioning' },
    ],
    rating: 4.9,
    reviewCount: 1,
    salesCount: 120,
    dateAdded: '2026-01-20',
    featured: true,
    promo: false,
  },
  {
    id: 'prod-5',
    name: 'Đồng Hồ Nam Thông Minh Slate Elite',
    description: 'Thiết kế mặt tròn sang trọng mạ titan nhẵn mịn, thời kháng nước sâu 50m. Đồng hành đắc lực để đo lường nhịp tim, giấc ngủ, định vị GPS, và kết nối nhanh chóng thông báo cuộc gọi.',
    categoryId: 'cat-accessory',
    brand: 'Cronos',
    originalPrice: 5500000,
    discountPrice: 4200000,
    image: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=80',
    ],
    colors: ['Đen không gian', 'Bạc hoàng gia'],
    sizes: ['42mm', '46mm'],
    variants: [
      { id: 'v20', color: 'Đen không gian', size: '42mm', stock: 12 },
      { id: 'v21', color: 'Đen không gian', size: '46mm', stock: 8 },
      { id: 'v22', color: 'Bạc hoàng gia', size: '42mm', stock: 6 },
      { id: 'v23', color: 'Bạc hoàng gia', size: '46mm', stock: 2 }, // Low stock!
    ],
    specs: [
      { label: 'Chống nước', value: '5 ATM (50 mét)' },
      { label: 'Độ rộng dây', value: '22 mm tinh tế' },
      { label: 'Màn hình', value: 'AMOLED 1.4 inch sắc nét' },
    ],
    rating: 4.2,
    reviewCount: 1,
    salesCount: 38,
    dateAdded: '2026-03-12',
    featured: false,
    promo: true,
  },
  {
    id: 'prod-6',
    name: 'Serum Dưỡng Thể Vitamin C Sáng Da',
    description: 'Serum dưỡng thể chiết xuất từ nho đen và Vitamin C tinh khiết giúp hồi phục collagen tự nhiên của da, giảm hắc sắc tố, nuôi dưỡng làn da căng mọng tràn đầy sức sống chỉ sau 14 ngày sử dụng.',
    categoryId: 'cat-cosmetics',
    brand: 'NaturaBody',
    originalPrice: 450000,
    discountPrice: 380000,
    image: [
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500&auto=format&fit=crop&q=80',
    ],
    colors: ['Tự nhiên'],
    sizes: ['150ml', '250ml'],
    variants: [
      { id: 'v24', color: 'Tự nhiên', size: '150ml', stock: 45 },
      { id: 'v25', color: 'Tự nhiên', size: '250ml', stock: 30 },
    ],
    specs: [
      { label: 'Dung tích', value: '150ml / 250ml' },
      { label: 'Độ PH lý tưởng', value: '5.5 dịu nhẹ' },
      { label: 'Loại da phù hợp', value: 'Mọi loại da kể cả da mẫn cảm' },
    ],
    rating: 4.6,
    reviewCount: 1,
    salesCount: 88,
    dateAdded: '2026-04-20',
    featured: false,
    promo: false,
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin',
    email: 'admin@ecommerce.vn',
    password: 'admin123',
    name: 'Nguyễn Quản Trị',
    phone: '0901234567',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    role: 'admin',
    active: true,
    joinedDate: '2026-01-01',
    addresses: [
      {
        id: 'addr-a1',
        name: 'Nguyễn Quản Trị',
        phone: '0901234567',
        label: 'Văn phòng chính',
        street: '123 Đường Lê Lợi, Phường Bến Thành, Quận 1',
        city: 'TP. Hồ Chí Minh',
      }
    ],
  },
  {
    id: 'usr-staff',
    email: 'kho@ecommerce.vn',
    password: 'kho123',
    name: 'Trần Thủ Kho',
    phone: '0987654321',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    role: 'staff_inventory',
    active: true,
    joinedDate: '2026-02-15',
    addresses: [
      {
        id: 'addr-s1',
        name: 'Kho hàng Tổng Công Ty',
        phone: '0987654321',
        label: 'Kho Trung Chuyển',
        street: '456 Đường Nguyễn Văn Linh, Quận 7',
        city: 'TP. Hồ Chí Minh',
      }
    ],
  },
  {
    id: 'usr-cust',
    email: 'customer@ecommerce.vn',
    password: 'customer123',
    name: 'Phạm Minh Quân',
    phone: '0912123123',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'customer',
    active: true,
    joinedDate: '2026-03-01',
    addresses: [
      {
        id: 'addr-c1',
        name: 'Phạm Minh Quân',
        phone: '0912123123',
        label: 'Nhà riêng',
        street: '789 Đường Kim Mã, Quận Ba Đình',
        city: 'Hà Nội',
      },
      {
        id: 'addr-c2',
        name: 'Phạm Minh Quân (Cty)',
        phone: '0900999888',
        label: 'Nơi làm việc',
        street: '15 Đường Nguyễn Huệ, Quận 1',
        city: 'TP. Hồ Chí Minh',
      }
    ],
  }
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'c-10',
    code: 'ECOM10',
    type: 'percent',
    value: 10,
    minOrder: 500000,
    expiryDate: '2026-12-31',
    active: true,
    usageLimit: 100,
    usageCount: 20,
  },
  {
    id: 'c-100k',
    code: 'GIAM100K09',
    type: 'fixed',
    value: 100000,
    minOrder: 1500000,
    expiryDate: '2026-12-31',
    active: true,
    usageLimit: 50,
    usageCount: 8,
  },
  {
    id: 'c-expired',
    code: 'QUADAOKIEU',
    type: 'percent',
    value: 50,
    minOrder: 200000,
    expiryDate: '2025-01-01',
    active: false,
    usageLimit: 10,
    usageCount: 10,
  }
];

export const INITIAL_BANNERS: Banner[] = [
  {
    id: 'b-1',
    title: 'SIÊU TIỆC ĐIỆN TỬ - APPLE WEEK',
    subtitle: 'Nâng cấp iPhone 15 Pro Max ngay hôm nay. Ưu đãi giảm thẳng tới 5 triệu đồng, trả góp 0% lãi suất.',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=1200&auto=format&fit=crop&q=80',
    link: 'cat-elec',
    active: true,
  },
  {
    id: 'b-2',
    title: 'THỜI TRANG ĐÓN HÈ - PHONG CÁCH CHẤT',
    subtitle: 'Bomber năng động, Sneaker bền bỉ cực sành điệu. Freeship Extra toàn quốc.',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200&auto=format&fit=crop&q=80',
    link: 'cat-fashion',
    active: true,
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-10001',
    userId: 'usr-cust',
    customerName: 'Phạm Minh Quân',
    customerEmail: 'customer@ecommerce.vn',
    customerPhone: '0912123123',
    items: [
      {
        productId: 'prod-4',
        name: 'Giày Thể Thao Sneaker Active Pro 2.0',
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop&q=80',
        selectedColor: 'Đỏ lửa',
        selectedSize: '41',
        price: 1590000,
        quantity: 1,
      }
    ],
    subTotal: 1590000,
    shippingFee: 30000,
    discountAmount: 100000,
    couponCode: 'GIAM100K09',
    total: 1520000,
    paymentMethod: 'VNPAY',
    shippingAddress: {
      id: 'addr-c1',
      name: 'Phạm Minh Quân',
      phone: '0912123123',
      label: 'Nhà riêng',
      street: '789 Đường Kim Mã, Quận Ba Đình',
      city: 'Hà Nội',
    },
    courier: 'Giao Hàng Nhanh (GHN)',
    status: 'completed',
    date: '2026-05-24T10:30:00Z',
  },
  {
    id: 'ORD-10002',
    userId: 'usr-cust',
    customerName: 'Phạm Minh Quân',
    customerEmail: 'customer@ecommerce.vn',
    customerPhone: '0912123123',
    items: [
      {
        productId: 'prod-2',
        name: 'Tai Nghe Không Dây Bose QuietComfort Ultra',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=80',
        selectedColor: 'Đan nhám',
        selectedSize: 'Tiêu chuẩn',
        price: 8990000,
        quantity: 1,
      },
      {
        productId: 'prod-6',
        name: 'Serum Dưỡng Thể Vitamin C Sáng Da',
        image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500&auto=format&fit=crop&q=80',
        selectedColor: 'Tự nhiên',
        selectedSize: '150ml',
        price: 380000,
        quantity: 2,
      }
    ],
    subTotal: 9750000,
    shippingFee: 40000,
    discountAmount: 0,
    total: 9790000,
    paymentMethod: 'COD',
    shippingAddress: {
      id: 'addr-c2',
      name: 'Phạm Minh Quân (Cty)',
      phone: '0900999888',
      label: 'Nơi làm việc',
      street: '15 Đường Nguyễn Huệ, Quận 1',
      city: 'TP. Hồ Chí Minh',
    },
    courier: 'Giao Hàng Tiết Kiệm (GHTK)',
    status: 'shipping',
    date: '2026-05-26T08:15:00Z',
  },
  {
    id: 'ORD-10003',
    userId: 'usr-cust',
    customerName: 'Phạm Minh Quân',
    customerEmail: 'customer@ecommerce.vn',
    customerPhone: '0912123123',
    items: [
      {
        productId: 'prod-3',
        name: 'Áo Khoác Bomber Da Lộn Classic',
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&auto=format&fit=crop&q=80',
        selectedColor: 'Nâu bò',
        selectedSize: 'M',
        price: 850000,
        quantity: 1,
      }
    ],
    subTotal: 850000,
    shippingFee: 30000,
    discountAmount: 85000,
    couponCode: 'ECOM10',
    total: 7950000,
    paymentMethod: 'MOMO',
    shippingAddress: {
      id: 'addr-c1',
      name: 'Phạm Minh Quân',
      phone: '0912123123',
      label: 'Nhà riêng',
      street: '789 Đường Kim Mã, Quận Ba Đình',
      city: 'Hà Nội',
    },
    courier: 'Giao Hàng Nhanh (GHN)',
    status: 'pending',
    date: '2026-05-27T14:45:00Z',
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    orderId: 'ORD-10001',
    productId: 'prod-4',
    userId: 'usr-cust',
    userName: 'Phạm Minh Quân',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Giày đi rất êm và nhẹ chân, chuẩn size giao hàng nhanh nhiệt tình. Sẽ ủng hộ shop lâu dài!',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&auto=format&fit=crop&q=80'],
    date: '2026-05-25T11:00:00Z',
  },
  {
    id: 'rev-2',
    orderId: 'ORD-10001',
    productId: 'prod-1',
    userId: 'usr-cust',
    userName: 'Phạm Minh Quân',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Máy mượt mà khung titan titan tự nhiên đỉnh cao lắm, chụp ảnh đẹp xuất sắc.',
    images: [],
    date: '2026-05-25T11:15:00Z',
  }
];
